font_family Input Mono Condensed Light
bold_font Input Mono Condensed Medium
font_size 12.0
modify_font underline_position 2
undercurl_style thick-dense

disable_ligatures always

include ./theme.conf
